version: '3'
services:
  gocd_server:
    image: "registry.fundacion-jala.local/devops/gocd/gocd-server:v18.5.0"
    ports:
      - "8153:8153"
      - "8154:8154"
    volumes:
      - /home/ubuntu/docker/godata_server:/godata
      - /home/ubuntu/docker/go_server:/home/go
  gocd_agent:
    image: "registry.fundacion-jala.local/devops/gocd/gocd-agent-alpine-3.7:v18.5.0"
    environment:
      - GO_SERVER_URL=https://gocd_server:8154/go
    volumes:
      - /home/ubuntu/docker/godata_agent:/godata
      - /home/ubuntu/docker/go_agent:/home/go
  sonarqube:
    image: "registry.fundacion-jala.local/devops/sonarqube:6.7.4-alpine"
    ports:
      - "9000:9000"
      - "9092:9092"
    volumes:
      - /home/ubuntu/sonarqube/sonarqube_conf:/opt/sonarqube/conf
      - /home/ubuntu/sonarqube/sonarqube_data:/opt/sonarqube/data
      - /home/ubuntu/sonarqube/sonarqube_extensions:/opt/sonarqube/extensions
      - /home/ubuntu/sonarqube/sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
