format_version: 3
pipelines:
  quickstart-yaml-config:
    lock_behavior: lockOnFailure
    group: JavaAPP
    materials:
      repo: 
       git: https://github.com/devops-at06/OH.git
       branch: master
    stages: 
      - Compile:
          jobs:
            assemble: 
              tasks:
                - exec:
                    command: ./gradle/quickstart/gradlew
                    arguments:
                      - "clean"
                      - "assemble"
                      - "-p"
                      - "gradle/quickstart"
      - Test:
          jobs:
            testing: 
              tasks:
                - exec:
                    command: ./gradle/quickstart/gradlew
                    arguments:
                      - clean
                      - test
                      - jacocoTestReport
                      - -p
                      - gradle/quickstart/
      - Publish:
          jobs:
            publishing: 
              tasks:
                - exec:
                    command: ./gradle/quickstart/gradlew
                    arguments:
                      - uploadArchives
                      - -p
                      - gradle/quickstart/
              artifacts:
                - build:
                    source: gradle/quickstart/repos/*.jar
                    destination: war
                - test:
                    source: gradle/quickstart/build/test-results/test/*xml
                    destination: xml
                - build:
                    source: gradle/quickstart/build/reports/coverage/*
                    destination: html_coverage
                - build:
                    source: gradle/quickstart/build/reports/tests/test/*
                    destination: html_report
              tabs:
                Cod_Coverage: html_coverage/index.html
                Test_Summary: html_report/index.html
