format_version: 3
pipelines:
  quickstart-yaml-config:
    lock_behavior: lockOnFailure
    group: JavaAPP
    materials:
      repo: 
       git: https://github.com/devops-at06/OH.git
       branch: master
    stages: 
      - Compile:
          jobs:
            assemble: 
              tasks:
                - exec:
                    command: ./gradle/quickstart/gradlew
                    arguments:
                      - "clean"
                      - "assemble"
                      - "-p"
                      - "gradle/quickstart"
      - Test:
          jobs:
            testing: 
              tasks:
                - exec:
                    command: ./gradle/quickstart/gradlew
                    arguments:
                      - clean
                      - test
                      - jacocoTestReport
                      - -p
                      - gradle/quickstart/
      - CodeQuality:
          jobs:
            sonarqube: 
              tasks:
                - exec:
                    command: ./gradle/quickstart/gradlew
                    arguments:
                      - sonarqube
                      - -Dsonar.host.url=http://127.0.0.1:9000
                      - -p
                      - gradle/quickstart/
      - Publish:
          jobs:
            publishing: 
              tasks:
                - exec:
                    command: ./gradle/quickstart/gradlew
                    arguments:
                      - uploadArchives
                      - -p
                      - gradle/quickstart/
              artifacts:
                - build:
                    source: gradle/quickstart/repos/*.jar
                    destination: war
                - test:
                    source: gradle/quickstart/build/test-results/test/*xml
                    destination: xml
                - build:
                    source: gradle/quickstart/build/reports/coverage/*
                    destination: html_coverage
                - build:
                    source: gradle/quickstart/build/reports/tests/test/*
                    destination: html_report
              tabs:
                Cod_Coverage: html_coverage/index.html
                Test_Summary: html_report/index.html
  
  webquickstart-yaml-config:
    lock_behavior: lockOnFailure
    group: WebJavaAPP
    materials:
      repo:
       git: https://github.com/devops-at06/OH.git
       branch: master
    stages:
      - Compile:
          jobs:
            assemble:
              tasks:
                - exec:
                    command: ./gradle/webquickstart/gradlew
                    arguments:
                      - "clean"
                      - "assemble"
                      - "-p"
                      - "gradle/webquickstart"
      - Test:
          jobs:
            unittests:
              tasks:
                - exec:
                    command: ./gradle/webquickstart/gradlew
                    arguments:
                      - test
                      - "-p"
                      - "gradle/webquickstart"
              artifacts:
                - test:
                    source: build/test-results/test/*xml
                    destination: xml
              artifacts:
                - build:
                    source: build/reports/tests/test/**/*
                    destination: html_report
              tabs:              
                Test_Summary: html_report/index.html
      - Publish:
          jobs:
            pucblishArtifact:
              tasks:
                - exec:
                    command: ./gradle/webquickstart/gradlew
                    arguments:
                      - uploadArchives
                      - "-p"
                      - "gradle/webquickstart"
              artifacts:
                - build:
                    source: repos/*.war
                    destination: war  
      - Deploy:
          jobs:
            deploying:
              tasks:
                - exec:
                    command: ./gradle/webquickstart/gradlew
                    arguments:
                      - -b
                      - deploy.gradle
                      - deploy
                      - -Ddev_server=10.28.135.233
                      - -Duser_server=ubuntu
                      - -Dkey_path=C:\\Users\\Administrator\\Desktop\\omy.pem
                      - -Dtomcat_webapps=/opt/tomcat/webapps
                      - -Dwar_path=build/libs
                      - -Dwar_name=webquickstart
                      - -p
                      - "gradle/webquickstart"
              artifacts:
                - build:
                    source: repos/*.war
                    destination: war       
